ALTER TABLE "Form"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'DRAFT',
ADD COLUMN IF NOT EXISTS "redirectUrl" TEXT,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Form"
SET "status" = CASE
  WHEN COALESCE("published", false) = true THEN 'LIVE'
  ELSE 'DRAFT'
END
WHERE "status" IS NULL OR "status" = '';

ALTER TABLE "Field"
ADD COLUMN IF NOT EXISTS "placeholder" TEXT,
ADD COLUMN IF NOT EXISTS "helperText" TEXT,
ADD COLUMN IF NOT EXISTS "hidden" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "options" JSONB,
ADD COLUMN IF NOT EXISTS "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
